"""
utils.py
========
Shared prediction utilities used by app.py.
Instructions:
    - Ensure image_fraud_model.h5, behavior_model.pkl, behavior_scaler.pkl
      exist in the same directory (generated by the two training scripts).
    - Import `predict_fraud` from this module.
"""

import os
import numpy as np
import pandas as pd
import joblib
import tensorflow as tf
from PIL import Image

# ── Configuration ─────────────────────────────────────────────────────────────
IMG_SIZE           = (128, 128)
IMAGE_MODEL_PATH   = "image_fraud_model.h5"
BEHAVIOR_MODEL_PATH = "behavior_model.pkl"
SCALER_PATH        = "behavior_scaler.pkl"

# Score weights (must sum to 1.0)
IMAGE_WEIGHT    = 0.6
BEHAVIOR_WEIGHT = 0.4

# Risk thresholds
THRESHOLD_LOW    = 0.35
THRESHOLD_HIGH   = 0.65

# ── Lazy-loaded model singletons ──────────────────────────────────────────────
_image_model    = None
_behavior_model = None
_scaler         = None
_feature_cols   = None


def _load_image_model():
    global _image_model
    if _image_model is None:
        if not os.path.exists(IMAGE_MODEL_PATH):
            raise FileNotFoundError(
                f"{IMAGE_MODEL_PATH} not found. Run train_image_model.py first."
            )
        _image_model = tf.keras.models.load_model(IMAGE_MODEL_PATH)
    return _image_model


def _load_behavior_model():
    global _behavior_model, _scaler, _feature_cols
    if _behavior_model is None:
        if not os.path.exists(BEHAVIOR_MODEL_PATH):
            raise FileNotFoundError(
                f"{BEHAVIOR_MODEL_PATH} not found. Run train_behavior_model.py first."
            )
        payload        = joblib.load(BEHAVIOR_MODEL_PATH)
        _behavior_model = payload["model"]
        _feature_cols  = payload["feature_cols"]
        _scaler        = joblib.load(SCALER_PATH)
    return _behavior_model, _scaler, _feature_cols


# ── Image Preprocessing ───────────────────────────────────────────────────────
def preprocess_image(image_path: str) -> np.ndarray:
    """
    Load an image from disk, resize to 128×128, normalise to [0,1].
    Returns a (1, 128, 128, 3) float32 array ready for the CNN.
    """
    img = Image.open(image_path).convert("RGB")
    img = img.resize(IMG_SIZE)
    arr = np.array(img, dtype=np.float32) / 255.0
    return np.expand_dims(arr, axis=0)   # Add batch dimension


# ── Behavior Feature Engineering (mirrors train_behavior_model.py) ────────────
def _engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["complaint_ratio"]      = df["total_refund_requests"] / (df["total_orders"] + 1)
    df["refund_per_complaint"]  = df["refund_amount_30d"] / (df["prev_complaints_30d"] + 1)
    df["new_addr_promo"]        = df["is_new_address"] * df["promo_applied"]
    df["value_per_item"]        = df["order_value"] / (df["num_items"] + 1)
    df["recent_refund_flag"]    = (df["days_since_last_refund"] < 7).astype(int)
    df["is_new_account"]        = (df["account_age_days"] < 60).astype(int)
    return df


def preprocess_behavior(user_data: dict) -> np.ndarray:
    """
    Accept a raw JSON dict of user features, apply feature engineering,
    encode categoricals, scale, and return a 2-D numpy array.
    """
    _, scaler, feature_cols = _load_behavior_model()

    # Defaults for every expected raw column (safe fallback)
    defaults = {
        "account_age_days": 180,
        "total_orders": 10,
        "total_refund_requests": 0,
        "order_value": 300.0,
        "num_items": 2,
        "is_peak_hour": 0,
        "delivery_time_min": 40,
        "distance_km": 5.0,
        "payment_method": "card",
        "is_new_address": 0,
        "promo_applied": 0,
        "restaurant_rating": 4.0,
        "driver_rating": 4.0,
        "prev_complaints_30d": 0,
        "prev_fraud_flags": 0,
        "refund_amount_30d": 0.0,
        "days_since_last_refund": 365,
    }

    # Merge incoming data over defaults (user values override)
    merged = {**defaults, **user_data}

    df = pd.DataFrame([merged])
    df = _engineer_features(df)

    # One-hot encode payment_method
    df = pd.get_dummies(df, columns=["payment_method"], drop_first=False)

    # Ensure all dummy columns exist
    for col in ["payment_method_card", "payment_method_cod",
                "payment_method_upi", "payment_method_wallet"]:
        if col not in df.columns:
            df[col] = 0

    # Align columns to training schema (fill missing with 0)
    for col in feature_cols:
        if col not in df.columns:
            df[col] = 0

    df = df[feature_cols].fillna(0)
    return scaler.transform(df)


# ── Core Prediction Function ──────────────────────────────────────────────────
def predict_fraud(image_path: str, user_data: dict) -> dict:
    """
    Run both models and return a combined fraud assessment.

    Parameters
    ----------
    image_path : str
        Absolute or relative path to the food image.
    user_data  : dict
        JSON-parsed dict of user/order behaviour features.

    Returns
    -------
    dict with keys:
        fraud_score  (float 0–1)
        risk_level   (str: 'LOW' | 'MEDIUM' | 'HIGH')
        image_score  (float 0–1)
        behavior_score (float 0–1)
    """
    # 1. Image model score
    image_model = _load_image_model()
    img_tensor  = preprocess_image(image_path)
    image_score = float(image_model.predict(img_tensor, verbose=0)[0][0])

    # 2. Behavior model score
    behavior_model, _, _ = _load_behavior_model()
    behavior_features    = preprocess_behavior(user_data)
    behavior_score       = float(behavior_model.predict_proba(behavior_features)[0][1])

    # 3. Weighted combination
    final_score = IMAGE_WEIGHT * image_score + BEHAVIOR_WEIGHT * behavior_score

    # 4. Risk bucketing
    if final_score < THRESHOLD_LOW:
        risk_level = "LOW"
    elif final_score < THRESHOLD_HIGH:
        risk_level = "MEDIUM"
    else:
        risk_level = "HIGH"

    return {
        "fraud_score"    : round(final_score, 4),
        "risk_level"     : risk_level,
        "image_score"    : round(image_score, 4),
        "behavior_score" : round(behavior_score, 4),
    }
